name: Snapshot CI

# Controls when the action will run. Triggers the workflow on push request
# events but only for the master branch
on:
  push:
    branches: [ 20200324-snapshot ]

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: vroy/gha-kotlin-linter@v2

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Run tests
      run: ./gradlew test
      
  publish:
    needs: [validate, test]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Publish snapshot
      run: |
        ./gradlew -Pversion=SNAPSHOT -PossrhUsername="${{ secrets.OSSRH_USERNAME }}" \
        -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}"  -PsigningKey="${{ secrets.GPG_KEY_CONTENTS }}" \
        -PsigningPassword="${{ secrets.GPG_KEY_PASSWORD }}" publishAllPublicationsToMavenCentralRepository
